# --- Change what appears in the banner --- #
title: Snap Spanish
description: Your optimum language loving & learning website.

# --- Change language of site --- #
lang: en

# --- List of links in the navigation bar --- #
# --- Only change these if you change the name of your .md files!! --- #
# --- And, only change the names of the HTML files e.g. page2.html --- #
github:
  page1: Home.html
  page2: Grammar.html
  page3: Culture.html
  page4: History.html
  page5: Numbers.html
